-- AlterTable User: micro goals + reminders
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyVitaminAGoal" DOUBLE PRECISION NOT NULL DEFAULT 900;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyVitaminCGoal" DOUBLE PRECISION NOT NULL DEFAULT 90;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyVitaminDGoal" DOUBLE PRECISION NOT NULL DEFAULT 20;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyCalciumGoal" DOUBLE PRECISION NOT NULL DEFAULT 1000;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyIronGoal" DOUBLE PRECISION NOT NULL DEFAULT 8;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "reminders" JSONB;

-- AlterTable Meal: favorites
ALTER TABLE "Meal" ADD COLUMN IF NOT EXISTS "isFavorite" BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Meal_userId_isFavorite_idx" ON "Meal"("userId", "isFavorite");
